# Generated by Django 2.2.6 on 2019-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
