# Generated by Django 2.2.6 on 2019-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191121_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssurl',
            name='Ссылка для ленты',
        ),
        migrations.AddField(
            model_name='rssurl',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rssurl',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка для ленты'),
        ),
    ]
