# Generated by Django 2.2.6 on 2019-11-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191121_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RssUrl',
            new_name='Rss',
        ),
    ]
