# Generated by Django 2.2.6 on 2019-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_post',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
